---
version: "2.12"
services:
  web:
    container_name: passwordresetcnt
    build: /pwReset
    image: passwordresetui:8
    ports:
      - 8088:80
    networks:
      mynetwork:
        ipv4_address: 192.168.0.88
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1 
